M48
; DRILL file KiCad 10.0.1 date 2026-05-08T17:52:31
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-08T17:52:31+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.500
%
G90
G05
T1
X105.8Y-78.138
X113.8Y-78.138
T2
X71.0Y-58.5
X71.0Y-80.5
X82.0Y-58.5
X82.0Y-80.5
T3
X74.14Y-40.56
X74.14Y-53.26
M30
